#!/bin/bash
# GitHub Secrets Setup Script
# This script helps you set up the required secrets for follow-builders-enhanced

echo "=== Follow Builders Enhanced - Secrets Setup ==="
echo ""
echo "You need to add the following secrets to your GitHub repository:"
echo "Repository: https://github.com/is361/follow-builders-enhanced/settings/secrets/actions"
echo ""
echo "1. X_BEARER_TOKEN"
echo "   - Get from: https://developer.x.com/en-us/dashboard"
echo "   - Create a project and app, then generate Bearer Token"
echo ""
echo "2. POD2TXT_API_KEY"
echo "   - Get from: https://pod2txt.vercel.app/"
echo "   - Register and get your API key"
echo ""
echo "=== Manual Setup Steps ==="
echo "1. Go to: https://github.com/is361/follow-builders-enhanced/settings/secrets/actions"
echo "2. Click 'New repository secret'"
echo "3. Add X_BEARER_TOKEN with your token value"
echo "4. Add POD2TXT_API_KEY with your API key value"
echo "5. Click 'Add secret'"
echo ""
echo "=== Verification ==="
echo "After adding secrets, test the workflow:"
echo "1. Go to: https://github.com/is361/follow-builders-enhanced/actions"
echo "2. Click 'Generate Enhanced Feeds'"
echo "3. Click 'Run workflow'"
echo "4. Wait for completion (1-2 minutes)"
echo "5. Check if feed-reddit.json and feed-youtube.json are generated"
